ARG sendgrid_key

FROM amd64/ubuntu as base



WORKDIR /build


RUN echo "sendgridKey: $sendgrid_key" > env.yaml

RUN . /home/nix/.nix-profile/etc/profile.d/nix.sh && \
      nix-shell ./nix/build.nix \
     --log-format bar-with-logs \ 
     --verbose --command \ 
     "./scripts/api-generator.sh sendgrid-openapiv3.yaml . Sendgrid sendgrid && \
     ./scripts/api-generator.sh sendgrid-openapiv3.yaml . Github github && \
      stack install --system-ghc --fast -j12 --test"

FROM base as main

EXPOSE 12000/tcp

WORKDIR /server

COPY env.yaml /server
COPY --from=server-build --chown=nix:nix /build/bin /server/bin
COPY --from=server-build --chown=nix:nix /build/deploy /server/deploy
COPY --from=server-build --chown=nix:nix /build/migration /server/migration
COPY --from=server-build --chown=nix:nix /build/tls /server/tls
COPY --from=server-build --chown=nix:nix /build/package.yaml /build/nix/deploy.nix /build/stack.yaml /build/Setup.hs /server/

ENTRYPOINT ["/server/deploy/init.sh"]