name: Docker Image for Backend

on: 
  push:
    branches: 
      - '*'
        # Pattern matched against refs/tags
    tags:        
      - '*' # Push events to every tag not containing /

jobs:
  
  push_to_google_registry:
    name: Push Docker image to Google
    environment: TTH_Google
    runs-on: ubuntu-latest
    steps:    
      - name: Check out the repo
        uses: actions/checkout@v3.5.2

                
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            sendgrid_key=$SENDGRID_KEY
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta_tag_1.outputs.tags }}
            ${{ steps.meta_branch_1.outputs.tags }}